services:

  backend:
    build: ./backend
    container_name: devsecops-backend
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
    environment:
      - FLASK_ENV=development
      - DB_PATH=/app/data/scans.db
      - JENKINS_URL=http://host.docker.internal:2000
      - JENKINS_USER=(USER_NAME)
      - JENKINS_TOKEN=(JENKINS_TOKEN)
      - JENKINS_JOB=(JENKINS_JOB_NAME)
      - GROQ_API_KEY=(API_KEY)
    networks:
      - devsecops-net

  frontend:
    build: ./frontend
    container_name: devsecops-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - devsecops-net

  sonarqube:
    image: sonarqube:community
    container_name: devsecops-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - devsecops-net

volumes:
  sqlite_data:
  sonarqube_data:
  sonarqube_logs:

networks:
  devsecops-net:
    driver: bridge
